---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Saiba mais sobre as alterações mais recentes nas cargas de trabalho que fazem parte do NetApp Workload Factory. 
---
= Mudanças recentes no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nas cargas de trabalho que fazem parte do NetApp Workload Factory.



== 04 de janeiro de 2026



=== Amazon FSX para NetApp ONTAP



==== Atualizações de análise bem arquitetadas

O Workload Factory analisa seus sistemas de arquivos FSx para ONTAP para as seguintes configurações:

* A proteção autônoma contra ransomware (ARP/AI) da NetApp desativada inclui dispositivos de bloco: verifica se o ARP/AI está desativado em volumes de dispositivos de bloco.
* Modo de gravação do relacionamento de cache: verifica se o modo de gravação é o ideal para a carga de trabalho do volume de cache.
* Exclusão de backups desnecessários: verifica se os backups estão desatualizados ou são desnecessários e podem ser excluídos para reduzir custos.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualize o status bem arquitetado do seu FSx para sistemas de arquivos ONTAP"]



==== Integração da página inicial do assistente de IA "Pergunte-me"

A página inicial do console do Workload Factory incorpora o assistente de IA "Pergunte-me", permitindo que você faça perguntas sobre seu próprio ambiente de armazenamento, obtenha insights personalizados diretamente do seu ambiente e consulte conversas anteriores. Você pode interagir com o recurso "Pergunte-me" para entender suas cargas de trabalho, solucionar problemas e aprender mais sobre o Workload Factory — tudo isso sem sair do console.



==== Utilização da entidade de usuário do IAM em políticas de permissão baseadas em recursos de vinculação do Lambda

Os links Lambda usados ​​para conectar sua conta do Workload Factory a um ou mais sistemas de arquivos FSx for ONTAP para executar operações avançadas do ONTAP agora usam a entidade de usuário do IAM para permissões de política baseadas em recursos. Essa mudança proporciona um melhor alinhamento com as melhores práticas do setor para acesso a recursos da AWS.



==== Adicionada tela de análise para o analisador de IA para eventos de emergência médica.

Uma nova tela de _Análise_ foi adicionada ao menu Armazenamento. A partir desta tela, você pode usar o analisador de IA para o recurso de eventos FSx para ONTAP EMS.



==== Aprimoramentos de dispositivos de bloco no NetApp Workload Factory

As seguintes melhorias foram implementadas para dispositivos de bloco.



===== Criação de dispositivo de bloco

O NetApp Workload Factory oferece suporte à criação de dispositivos de bloco usando o protocolo iSCSI em sistemas de arquivos FSx para ONTAP , permitindo que você ofereça melhor suporte aos seus aplicativos de linha de negócios (LOB) a partir do console do Workload Factory.



===== Melhorias no gerenciamento de dispositivos de bloco

O NetApp Workload Factory inclui os seguintes aprimoramentos para link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gerenciando dispositivos de bloco"]. Agora você pode executar as seguintes tarefas no console do Workload Factory:

* Gerenciar o acesso do cliente
* Dados do dispositivo de bloco de arquivamento
* Excluir dispositivo de bloco




===== Suporte para ARP/AI em volumes FlexVol que contêm dispositivos de bloco

Você pode ativar link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Proteção autônoma contra ransomware da NetApp com IA (ARP/AI)"] em volumes FlexVol que contêm dispositivos de bloco. Habilitar o ARP/AI detecta ataques de ransomware usando IA e auxilia na recuperação de dados.



=== Workloads de banco de dados



==== Integração da página inicial do assistente de IA "Pergunte-me"

A página inicial do console do Workload Factory incorpora o assistente de IA "Pergunte-me", permitindo que você faça perguntas sobre seu próprio ambiente de armazenamento, obtenha insights personalizados diretamente do seu ambiente e consulte conversas anteriores. Você pode interagir com o recurso "Pergunte-me" para entender suas cargas de trabalho, solucionar problemas e aprender mais sobre o Workload Factory — tudo isso sem sair do console.



=== Workloads da VMware



==== Integração da página inicial do assistente de IA "Pergunte-me"

A página inicial do console do Workload Factory incorpora o assistente de IA "Pergunte-me", permitindo que você faça perguntas sobre seu próprio ambiente de armazenamento, obtenha insights personalizados diretamente do seu ambiente e consulte conversas anteriores. Você pode interagir com o recurso "Pergunte-me" para entender suas cargas de trabalho, solucionar problemas e aprender mais sobre o Workload Factory — tudo isso sem sair do console.



== 18 de dezembro de 2025



=== Workloads de banco de dados



==== Melhorias na integração com o Active Directory

O Workload Factory for Databases inclui três novos campos do Active Directory (AD) ao implantar o Microsoft SQL Server usando a opção *Criação avançada*. Essas melhorias permitem especificar as preferências de ingresso no Active Directory e usar uma conta de serviço gerenciada.

Os novos campos do AD são:

* Controlador de domínio preferencial
* Caminho preferencial da unidade organizacional
* Grupo de destino do Active Directory


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Implantar o Microsoft SQL Server"]



== 04 de dezembro de 2025



=== Amazon FSX para NetApp ONTAP



==== Suporte para pontos de acesso AWS S3 para FSx para ONTAP

O NetApp Workload Factory oferece suporte a pontos de acesso AWS S3 para seus sistemas de arquivos FSx for ONTAP . Você pode criar volumes usando pontos de acesso S3, atribuir pontos de acesso S3 a um volume existente e gerenciar pontos de acesso S3 a partir do console do Workload Factory. Utilizando um ponto de acesso S3, você pode acessar dados de arquivos residentes em volumes SMB/CIFS ou NFS por meio das APIs do AWS S3. Isso permite integrar seus dados existentes com GenAI, ML e análises de serviços da AWS que suportam pontos de acesso S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crie um volume usando pontos de acesso S3."]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gerenciar pontos de acesso S3 para um volume"]




== 27 de novembro de 2025



=== Amazon FSX para NetApp ONTAP



==== Suporte a dispositivos de bloco no NetApp Workload Factory

Gerencie seus dispositivos de bloco com mais eficiência graças ao novo suporte a dispositivos de bloco introduzido no NetApp Workload Factory. Este recurso permite visualizar detalhes e aumentar a capacidade dos LUNs iSCSI, proporcionando maior flexibilidade para suas necessidades de armazenamento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Gerencie dispositivos de bloco no Workload Factory"]



==== Atualizações de análise bem arquitetadas

O Workload Factory analisa seus sistemas de arquivos FSx para ONTAP para as seguintes configurações:

* Exclusão desnecessária de snapshots: verifica se os volumes possuem snapshots desatualizados e desnecessários que podem ser excluídos para reduzir custos.
* Reequilíbrio de volumes do FlexGroup : verifica se os volumes do FlexGroup estão distribuídos uniformemente entre os volumes de seus membros para garantir o desempenho ideal.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualize o status bem arquitetado do seu FSx para sistemas de arquivos ONTAP"]



==== Analisador de IA para eventos EMS no NetApp Workload Factory

O NetApp Workload Factory apresenta um analisador com inteligência artificial para eventos do ONTAP Event Management System (EMS). Essa funcionalidade ajuda você a identificar e solucionar problemas rapidamente, fornecendo informações e recomendações com base na análise dos dados de eventos do EMS.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analise os eventos do EMS no Workload Factory."]



==== Monitore as tendências de custo e uso do FSx para sistemas de arquivos ONTAP.

Você pode monitorar as tendências de custo e uso dos seus sistemas de arquivos FSx para ONTAP diretamente do console do NetApp Workload Factory . Essa funcionalidade fornece métricas de consumo e custo de armazenamento, além de custos detalhados, ajudando você a otimizar a alocação de recursos e o planejamento orçamentário.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Acompanhe os custos do FSx para sistemas de arquivos ONTAP no Workload Factory."]



==== Gerencie tags FSx para um sistema de arquivos no NetApp Workload Factory.

Gerencie facilmente suas tags FSx para um sistema de arquivos diretamente do console do NetApp Workload Factory . Este recurso permite adicionar, editar ou remover tags, possibilitando melhor organização e categorização dos seus sistemas de arquivos FSx para ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Gerencie as tags FSx no Workload Factory."]



==== Ajuste a capacidade de cache para o FSx para sistemas de arquivos ONTAP.

Você pode aumentar e diminuir a capacidade dos volumes de cache no console do Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gerencie volumes de cache no Workload Factory"]



=== Workloads de banco de dados



==== Otimize a economia na calculadora de bancos de dados para o Amazon Elastic Block Store (EBS).

Duas novas funcionalidades da calculadora melhoram a análise de economia de custos ao executar várias instâncias com armazenamento EBS, para que você possa economizar mais ao migrar para o FSx for ONTAP.

* O Workload Factory oferece uma solução de armazenamento consolidada para vários hosts de banco de dados em um único sistema de arquivos FSx para ONTAP . Essa consolidação otimiza os custos de armazenamento, reduzindo o número de sistemas de arquivos necessários para vários hosts de banco de dados, o que leva a uma maior economia de custos.
* O Workload Factory analisa o uso de desempenho do seu EBS e, em seguida, sugere a configuração FSx para ONTAP mais adequada e econômica.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Descubra as economias para hosts EBS detectados."]



==== Relatório em Excel disponível para o painel de controle bem estruturado.

Você pode baixar um relatório em Excel do painel de controle bem estruturado. O relatório apresenta o status de arquitetura adequada para o recurso de banco de dados e recomendações para todas as configurações de recursos, incluindo subconfigurações para sistema operacional e ONTAP.



==== Analisador de logs de erros disponível para bancos de dados Oracle.

O analisador de logs de erros Agentic, baseado em IA, está disponível para bancos de dados Oracle. O recurso utiliza algoritmos avançados de aprendizado de máquina para detectar e analisar automaticamente erros em arquivos de log. Esta ferramenta tem como objetivo agilizar o processo de solução de problemas, fornecendo aos desenvolvedores insights e recomendações práticas com base nos padrões identificados nos logs.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Saiba mais sobre o analisador de log de erros com tecnologia de IA da Agentic"]



==== Análise bem arquitetada para Oracle

A análise bem arquitetada inclui duas novas configurações de dimensionamento de armazenamento. A análise avalia e corrige problemas de configuração relacionados à alocação de espaço de troca (swap) e à capacidade disponível do sistema de arquivos para implementações existentes de bancos de dados Oracle.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configurações de banco de dados bem arquitetadas no Workload Factory"]



=== Workloads da VMware



==== Calcule a economia de custos da migração para o Amazon Elastic VMware Service em regiões específicas.

Agora você pode explorar o valor de diferentes opções de implantação para sua migração para a nuvem, otimizar os esforços investidos na avaliação de soluções e analisar em detalhes as soluções que têm o potencial de gerar valor e economia na nuvem.

Você também pode analisar a economia de núcleos de vCPU que pode ser alcançada usando o FSx para ONTAP em uma implementação EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Descubra como economizar no Amazon Elastic VMware Service com o NetApp Workload Factory."]



=== Configuração e administração



==== Atualização de permissões para o armazenamento.

O analisador de eventos do FSx para ONTAP EMS usa as seguintes permissões do Amazon Bedrock na política de permissões _operações e remediação_ para buscar dados de eventos para a carga de trabalho de armazenamento.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro de alterações de referência de permissões"]



== 02 de novembro de 2025



=== Amazon FSX para NetApp ONTAP



==== Gerenciamento de volume de cache

Você pode executar as seguintes operações de gerenciamento de volume de cache no console do Workload Factory:

* Editar o nome do cache
* Aumentar a capacidade de um volume de cache
* Edite o caminho de montagem ou a política de exportação para um volume de cache.
* Alterar o método ou modo de cache para um volume de cache.
* Pré-popular um volume de cache
* Excluir um volume de cache


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gerenciar volumes de cache"]



==== Gerenciamento automático de inodes disponível

Você pode habilitar o gerenciamento automático de inodes sem a necessidade de habilitar o gerenciamento automático de capacidade.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Ativar o gerenciamento automático de inodes"]



==== Configuração de aviso de limite para uso de capacidade e inodes.

Avisos de limite estão disponíveis tanto para capacidade quanto para uso de inodes. Você pode definir esses limites ao ativar o gerenciamento automático de capacidade ou de inodes. Para usar essa configuração, você precisará configurar as notificações usando olink:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Serviço de notificação do NetApp Workload Factory"^] .



==== redução do tamanho do volume disponível

É possível diminuir o tamanho dos volumes NFS e SMB/CIFS no NetApp Workload Factory. Essa funcionalidade permite um melhor gerenciamento dos recursos de armazenamento, possibilitando a redução do tamanho de volumes que não são mais necessários em sua capacidade atual.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Diminuir a capacidade de um volume"]



==== FSx aprimorado para estado de recurso ONTAP

O Workload Factory aprimorou o estado de recurso "mal configurado" para incluir uma explicação do problema real do recurso.



==== Atualizações de análise bem arquitetadas

O Workload Factory analisa seus sistemas de arquivos FSx para ONTAP para as seguintes configurações:

* Utilização do volume próxima do limite: verifica se algum volume está utilizando 80% ou mais de sua capacidade de armazenamento. Isso ajuda a identificar volumes que podem precisar de capacidade adicional.
* Acesso não autorizado a volumes: verifica se um volume iSCSI está acessível usando um caminho de montagem NFS ou SMB/CIFS e permite remover o acesso não autorizado ao volume para evitar riscos de segurança.




==== Alterações de permissões para o Workload Factory para armazenamento

O Workload Factory oferece mais clareza sobre as permissões necessárias para ações específicas e permite selecionar apenas as permissões de que você precisa. Ao adicionar credenciais, você terá três opções de permissões para escolher, em vez do modelo de permissões anterior, que era _somente leitura_ e _leitura/gravação_. O novo modelo de permissões divide as políticas de permissão da seguinte forma:

* _Visualização, planejamento e análise_: Visualize os sistemas de arquivos FSx para ONTAP , aprenda sobre a integridade do sistema, obtenha uma análise bem arquitetada para seus sistemas e explore oportunidades de economia.
* _Operações e correção_: Execute tarefas operacionais como ajustar a capacidade do sistema de arquivos e corrigir problemas nas configurações do seu sistema de arquivos.
* _Criação e exclusão de sistemas de arquivos_: Crie e exclua sistemas de arquivos FSx para ONTAP e VMs de armazenamento.


Ao adicionar credenciais, você pode selecionar uma ou mais dessas políticas de permissão com base no nível de acesso que deseja fornecer ao Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões do Workload Factory"]



==== Suporte ao cofre cibernético FSx para ONTAP

Você pode criar um cofre cibernético usando o FSx para ONTAP como origem ou destino na arquitetura do cofre cibernético. Os cofres cibernéticos oferecem um ambiente seguro e isolado para armazenar dados críticos, protegendo-os contra ransomware e outras ameaças cibernéticas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Configure um cofre cibernético com FSx para ONTAP."]



=== Workloads de banco de dados



==== Melhorias no painel de controle

O novo painel de controle foi simplificado e melhor organizado para fornecer uma visão geral mais clara dos seus recursos de banco de dados e das principais funcionalidades do Workload Factory em uma única tela; um cartão destaca os recursos do banco de dados, um cartão fornece informações sobre a pontuação e análise de arquitetura adequada, um cartão exibe a análise de erros, dois cartões exibem o custo mensal e a economia potencial, e um cartão exibe informações sobre os ambientes de teste (sandboxes).



==== Análise bem arquitetada para Oracle

A análise bem arquitetada inclui as seguintes avaliações e correções para configurações do Oracle:

* Sistema operacional de configuração de armazenamento usando o protocolo NFS: avalia e corrige problemas de configuração do NFS em implantações de banco de dados Oracle existentes.
* Sistema operacional de configuração de armazenamento usando o protocolo iSCSI: avalia e corrige problemas de configuração iSCSI em implantações de banco de dados Oracle existentes.
* Sistema operacional de configuração de armazenamento usando o Automatic Storage Management (ASM): avalia problemas de configuração com o ASM em implementações de banco de dados Oracle existentes.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementar configurações de banco de dados bem arquitetadas no Workload Factory"]



==== Alterações de permissões para o Workload Factory para Bancos de Dados

O Workload Factory for Databases atualizou as políticas de permissões para fornecer mais clareza sobre o que é necessário para ações específicas e granularidade para selecionar apenas as permissões de que você precisa. Ao adicionar credenciais, você terá três opções de permissões para escolher, em vez do modelo de permissões anterior, que era _somente leitura_ e _leitura/gravação_. O novo modelo de permissões divide as políticas de permissão da seguinte forma:

* _Visualização, planejamento e análise_: visualize o inventário de recursos do banco de dados, saiba mais sobre a integridade dos seus recursos, revise a análise bem arquitetada das suas configurações de banco de dados, obtenha análises de logs de erros e explore oportunidades de economia.
* _Operações e correção_: execute tarefas operacionais para seus recursos de banco de dados e corrija problemas de configuração do banco de dados e do sistema de arquivos FSx para ONTAP subjacente.
* _Criação de hosts de banco de dados_: implante os hosts de banco de dados e o armazenamento do sistema de arquivos FSx para ONTAP subjacente de acordo com as melhores práticas.


Ao adicionar credenciais, você pode selecionar uma ou mais dessas políticas de permissão com base no nível de acesso que deseja fornecer ao Workload Factory for Databases.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões do Workload Factory"^]



==== Painel de controle bem projetado adicionado.

Uma nova tela de painel de controle _Bem arquitetada_ foi adicionada ao menu Bancos de Dados. Nessa tela, você pode obter uma visão geral do status de configuração de todo o seu conjunto de bancos de dados.



==== Proteção contra edição para implantações de banco de dados no NetApp Backup and Recovery.

A partir do console do Workload Factory, você pode selecionar a opção para editar a proteção de um recurso protegido e, em seguida, será redirecionado para o Backup e Recuperação no NetApp Console , onde poderá modificar a política ou o agendamento de proteção.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["Proteção contra edições para implantações de banco de dados"]



==== Filtragem de erros por tags disponível para o recurso de análise de erros.

Ao usar o recurso de análise de erros no Workload Factory, você pode filtrar e visualizar os logs de erros do Microsoft SQL Server por tags orientadas à infraestrutura. Essa melhoria ajuda você a triar, solucionar e resolver problemas rapidamente.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Analise os registros de erros com filtragem por tags."^]



=== Workloads da VMware



==== Apresentando as preferências do Amazon Elastic VMware Service no assistente de implantação do sistema de arquivos FSx para ONTAP .

Ao implantar um sistema de arquivos FSx para ONTAP para ser usado como armazenamento de dados NFS externo para o Amazon Elastic VMware Service, agora você pode selecionar o ambiente EVS ao qual os armazenamentos de dados serão conectados. Isso preenche automaticamente vários campos no assistente de implantação para simplificar o processo de implantação.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Implante o sistema de arquivos FSx recomendado para ONTAP."]



==== Alterações de permissões para cargas de trabalho do VMware

As cargas de trabalho da VMware oferecem mais clareza sobre as permissões necessárias para ações específicas e granularidade para selecionar apenas as permissões de que você precisa. Ao adicionar credenciais, você terá duas opções de permissões para escolher, em vez do modelo de permissões anterior, que era _somente leitura_ e _leitura/gravação_. O novo modelo de permissões divide as políticas de permissão da seguinte forma:

* _Visualização, planejamento e análise_: Visualize o inventário de ambientes de virtualização da EVS, obtenha uma análise bem arquitetada para seus sistemas e explore oportunidades de economia.
* _Implantação e conectividade do armazenamento de dados_: Implante os layouts de VM recomendados em clusters Amazon EVS, Amazon EC2 ou VMware Cloud on AWS vSphere e use sistemas de arquivos Amazon FSx for NetApp ONTAP como armazenamentos de dados externos.


Ao adicionar credenciais, você pode selecionar uma ou mais dessas políticas de permissão com base no nível de acesso que deseja fornecer às cargas de trabalho do VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões do Workload Factory"^]



==== Melhorias no consultor de migração do Amazon EC2

Esta versão do NetApp Workload Factory para VMware apresenta diversas melhorias na experiência do assistente de migração:

* *Salvar ou baixar um plano de migração*: Agora você pode salvar ou baixar um plano de migração como um arquivo PDF ou CSV. Ao salvar um plano de migração, o plano é salvo em sua conta do Workload Factory.




=== Configuração e administração



==== Atualização de permissões

Nesta versão, fizemos atualizações significativas nas políticas de permissão para cargas de trabalho de armazenamento, banco de dados e VMware, a fim de aprimorar a segurança e o controle do usuário. Você pode personalizar suas configurações de permissão de forma mais detalhada, adicionando ou removendo permissões conforme achar melhor.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões para o Workload Factory"]



==== Nova notificação para armazenamento

O serviço de notificação do NetApp Workload Factory inclui a notificação para gerenciamento automático de inodes para armazenamento.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notificações para NetApp Workload Factory"]



==== Avisos de limite para gerenciamento automático de capacidade e inodes.

O gerenciamento automático de capacidade e inodes para armazenamento pode ser configurado com um limite de alerta que aciona uma notificação do serviço de notificação do Workload Factory. Para usar esse recurso, você precisa primeiro ativar o serviço de notificação do Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configure as notificações para o NetApp Workload Factory."]
