= A otimização contínua adiciona correção e avaliação de computação
:allow-uri-read: 




=== A otimização contínua adiciona correção e avaliação de computação

Os bancos de dados agora fornecem insights e recomendações para ajudá-lo a otimizar recursos de computação para instâncias do Microsoft SQL Server. Medimos a utilização da CPU e aproveitamos o serviço AWS Compute Optimizer para recomendar os tipos de instância ideais de tamanho certo e notificá-lo sobre patches de sistema operacional disponíveis. A otimização dos recursos de computação pode ajudar você a tomar decisões conscientes sobre os tipos de instâncias, o que resulta em economia de custos e utilização eficiente de recursos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Otimizar configurações de recursos de computação"]



=== Suporte ao PostgreSQL

Agora você pode implantar e gerenciar implantações de servidor PostgreSQL independentes em bancos de dados.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Crie um servidor PostgreSQL"]
