= Gerenciamento automático de capacidade para sistemas com escalabilidade horizontal
:allow-uri-read: 




=== Gerenciamento automático de capacidade para sistemas com escalabilidade horizontal

A fábrica de carga de trabalho agora procura inodes disponíveis em volumes e aumenta sua contagem de acordo com os limites configurados de gerenciamento automático de capacidade. Esse recurso é compatível com o gerenciamento automático de capacidade para sistemas com escalabilidade horizontal. Você pode habilitar o gerenciamento inodes como parte do gerenciamento automático de capacidade.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Ativar o gerenciamento automático de capacidade"]



=== API FlexGroup Rebalanceance

O workload da BlueXP  libera de fábrica a API FlexGroup Rebalanceance que permite executar um plano para rebalancear os dados em um FlexGroup. O rebalanceamento redistribui os dados uniformemente para os volumes dos membros.

link:https://console.workloads.netapp.com/api-doc["Documentação da API de fábrica do workload do BlueXP"]



=== O formulário de replicação de dados inclui casos de uso

O formulário de replicação de dados agora inclui casos de uso para facilitar o preenchimento do formulário. Você selecionará um dos seguintes casos de uso para replicação de dados: Migração, recuperação de desastres quentes, recuperação de desastres inativos, arquivamento ou outro. Depois de selecionar um caso de uso, a fábrica de carga de trabalho recomenda valores de acordo com as práticas recomendadas. Você pode aceitar os valores pré-selecionados ou personalizar os valores no formulário.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replique dados"]



=== Alterações na terminologia da política de disposição em camadas de dados

Agora, quando você seleciona uma política de disposição em categorias durante a criação de volume, replicação de dados ou atualizações de políticas de disposição em camadas existentes, você encontrará novos termos para descrever as políticas de disposição em categorias.

* _Balanced (Auto)_
* _Otimizado para custos (todos)_
* _Desempenho otimizado (somente Snapshots)_

