= Gerenciamento de volume de cache
:allow-uri-read: 




=== Gerenciamento de volume de cache

Você pode executar as seguintes operações de gerenciamento de volume de cache no console do Workload Factory:

* Editar o nome do cache
* Aumentar a capacidade de um volume de cache
* Edite o caminho de montagem ou a política de exportação para um volume de cache.
* Alterar o método ou modo de cache para um volume de cache.
* Pré-popular um volume de cache
* Excluir um volume de cache


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gerenciar volumes de cache"^]



=== Gerenciamento automático de inodes disponível

Você pode habilitar o gerenciamento automático de inodes sem a necessidade de habilitar o gerenciamento automático de capacidade.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Ativar o gerenciamento automático de inodes"^]



=== Configuração de aviso de limite para uso de capacidade e inodes.

Avisos de limite estão disponíveis tanto para capacidade quanto para uso de inodes. Você pode definir esses limites ao ativar o gerenciamento automático de capacidade ou de inodes. Para usar essa configuração, você precisará configurar as notificações usando olink:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Serviço de notificação do NetApp Workload Factory"^] .



=== redução do tamanho do volume disponível

É possível diminuir o tamanho dos volumes NFS e SMB/CIFS no NetApp Workload Factory. Essa funcionalidade permite um melhor gerenciamento dos recursos de armazenamento, possibilitando a redução do tamanho de volumes que não são mais necessários em sua capacidade atual.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Diminuir a capacidade de um volume"^]



=== FSx aprimorado para estado de recurso ONTAP

O Workload Factory aprimorou o estado de recurso "mal configurado" para incluir uma explicação do problema real do recurso.



=== Atualizações de análise bem arquitetadas

O Workload Factory analisa seus sistemas de arquivos FSx para ONTAP para as seguintes configurações:

* Utilização do volume próxima do limite: verifica se algum volume está utilizando 80% ou mais de sua capacidade de armazenamento. Isso ajuda a identificar volumes que podem precisar de capacidade adicional.
* Acesso não autorizado a volumes: verifica se um volume iSCSI está acessível usando um caminho de montagem NFS ou SMB/CIFS e permite remover o acesso não autorizado ao volume para evitar riscos de segurança.




=== Alterações de permissões para o Workload Factory para armazenamento

O Workload Factory oferece mais clareza sobre as permissões necessárias para ações específicas e permite selecionar apenas as permissões de que você precisa. Ao adicionar credenciais, você terá três opções de permissões para escolher, em vez do modelo de permissões anterior, que era _somente leitura_ e _leitura/gravação_. O novo modelo de permissões divide as políticas de permissão da seguinte forma:

* _Visualização, planejamento e análise_: Visualize os sistemas de arquivos FSx para ONTAP , aprenda sobre a integridade do sistema, obtenha uma análise bem arquitetada para seus sistemas e explore oportunidades de economia.
* _Operações e correção_: Execute tarefas operacionais como ajustar a capacidade do sistema de arquivos e corrigir problemas nas configurações do seu sistema de arquivos.
* _Criação e exclusão de sistemas de arquivos_: Crie e exclua sistemas de arquivos FSx para ONTAP e VMs de armazenamento.


Ao adicionar credenciais, você pode selecionar uma ou mais dessas políticas de permissão com base no nível de acesso que deseja fornecer ao Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões do Workload Factory"^]



=== Suporte ao cofre cibernético FSx para ONTAP

Você pode criar um cofre cibernético usando o FSx para ONTAP como origem ou destino na arquitetura do cofre cibernético. Os cofres cibernéticos oferecem um ambiente seguro e isolado para armazenar dados críticos, protegendo-os contra ransomware e outras ameaças cibernéticas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Configure um cofre cibernético com FSx para ONTAP."^]
