= Otimize as economias na calculadora de armazenamento para Amazon Elastic Block Store (EBS)
:allow-uri-read: 




=== Otimize as economias na calculadora de armazenamento para Amazon Elastic Block Store (EBS)

O Workload Factory pode analisar o uso do desempenho do seu EBS e então sugerir a melhor e mais econômica configuração do FSx para ONTAP para que você possa economizar mais mudando para o FSx para ONTAP.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html#explore-savings-for-detected-storage-environments["Explore economias para ambientes de armazenamento detectados no console do Workload Factory"]



=== Acesso rápido à tela de recursos do inventário do sistema de arquivos

Você pode navegar rapidamente para uma tela de recursos do sistema de arquivos FSx for ONTAP selecionando o nome do sistema de arquivos, agora um hiperlink, no inventário do FSx for ONTAP .



=== Descubra relacionamentos de cache no console do Workload Factory

Se você tiver relacionamentos _cache_ entre o sistema de arquivos FSx for ONTAP e outro tipo de armazenamento ONTAP (sistema local, Cloud Volumes ONTAP e FSx for ONTAP), poderá descobri-los e visualizá-los no console do Workload Factory. Isso permite que você entenda melhor os fluxos de dados, otimize a utilização do cache e melhore a eficiência em ambientes distribuídos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/discover-cache-volumes.html["Descubra e visualize relacionamentos de cache no console do Workload Factory"]



=== Atualização de análise bem arquitetada

O Workload Factory agora analisa seus sistemas de arquivos FSx for ONTAP para a seguinte configuração:

Limite de utilização da capacidade do arquivo de volume: verifica se os limites de capacidade do arquivo estão definidos como 80% ou menos. Isso ajuda a evitar a falta de espaço nos seus sistemas de arquivos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualize o status bem arquitetado do seu FSx para sistemas de arquivos ONTAP"]



==== Melhorias nas ações para problemas de configuração

Na guia *Análise bem arquitetada* no painel de um sistema de arquivos FSx para ONTAP , em vez de descartar uma configuração inteira para um sistema de arquivos, você também pode selecionar um ou mais volumes dentro de um sistema de arquivos para corrigir, descartar ou reativar.



=== Notificação adicional para armazenamento

O serviço de notificação do NetApp Workload Factory inclui a notificação semanal de problemas de configuração bem arquitetados.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html#notification-types-and-messages["Tipos de notificação e mensagens na documentação de configuração e administração do Workload Factory"]



=== Arquivos imutáveis suportam exclusão privilegiada

Com esse recurso, você pode configurar acesso privilegiado de exclusão para arquivos imutáveis ​​em seus sistemas de arquivos FSx for ONTAP . Isso permite que você proteja dados críticos contra exclusão acidental ou maliciosa, ao mesmo tempo em que permite que usuários autorizados substituam o bloqueio e excluam esses arquivos conforme necessário. A habilitação da exclusão privilegiada está disponível durante a criação do volume ou para volumes existentes.
