= Melhorias no gerenciamento automático de capacidade
:allow-uri-read: 




=== Melhorias no gerenciamento automático de capacidade

Quando o gerenciamento automático de capacidade está ativado, a fábrica de workloads da BlueXP  verifica se um sistema de arquivos atingiu seu limite de capacidade a cada 30 minutos, em vez de a cada 2 horas.

A configuração de IOPS provisionadas não é mais afetada quando o limite de capacidade é atingido.



=== Instantâneos imutáveis

Agora você pode bloquear snapshots, tornando-os imutáveis, por um período de retenção específico. O bloqueio impede o acesso não autorizado e as exclusões maliciosas de instantâneos. Você pode habilitar snapshots imutáveis durante a criação de políticas de snapshot, ao criar snapshots manuais e após a criação de snapshots.



=== Atualização de ficheiros imutáveis

Agora você pode fazer as seguintes alterações na configuração de arquivos imutáveis: Política de retenção, período de retenção, período de confirmação automática e modo de adição de volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["Gerenciar arquivos imutáveis"]



=== Aprimoramentos na replicação de dados

* Replicação entre contas: A replicação entre duas contas da AWS é compatível com o console de fábrica do workload do BlueXP , bem como o gerenciamento de replicação.
* Pausar e retomar a replicação: Você pode pausar (quiesce) atualizações de replicação agendadas do volume de origem para o volume de destino e, em seguida, retomar a programação de replicação quando estiver pronto. Durante a pausa, os volumes de origem e destino tornam-se independentes e o volume de destino faz a transição de somente leitura para leitura e gravação.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["Pausar e retomar uma relação de replicação"]





=== Eventos CloudShell no Tracker

Agora você pode rastrear eventos do CloudShell no Tracker.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Saiba como monitorar e rastrear operações com o Tracker"]
