= Melhorias na otimização
:allow-uri-read: 




=== Melhorias na otimização

Novas avaliações de otimização, correções e a exibição de vários recursos estão disponíveis ao otimizar seus ambientes de banco de dados.



==== Avaliações de resiliência

Os aprimoramentos incluem novas avaliações de resiliência para verificar se os recursos de redundância de dados e recuperação de desastres estão configurados para seus ambientes de banco de dados.

* Backups do FSX para ONTAP: Analisa se os sistemas de arquivos FSX for ONTAP que atendem os volumes da instância do SQL Server são configurados com backups programados do FSX para ONTAP.
* Replicação entre regiões: Avalia se o FSX para sistemas de arquivos ONTAP que atendem instâncias do Microsoft SQL Server estão configurados com replicação entre regiões.




==== Correção de computação

A correção de Receive Side Scaling (RSS) configura o RSS para distribuir o processamento de rede entre vários processadores e garantir uma distribuição de carga eficiente.



==== Correção de snapshot local

Define políticas de snapshot para volumes para suas instâncias do Microsoft SQL Server para manter seus ambientes de banco de dados resilientes em caso de perda de dados.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Otimizar configurações"]



==== Suporte para seleção múltipla de recursos

Ao otimizar as configurações do banco de dados, você poderá selecionar recursos específicos em vez de todos os recursos.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Otimizar configurações"]



=== Visualização de inventário melhorada

A guia Inventário no console de fábrica de carga de trabalho foi simplificada para que ele contenha apenas servidores SQL executados no Amazon FSX for NetApp ONTAP. Agora você encontrará servidores SQL no local e em execução na Amazon Elastic Block Store e no Amazon FSX for Windows File Server na guia explorar economia.



=== Criação rápida disponível para a implantação do servidor PostgreSQL

Você pode usar essa opção de implantação rápida para criar um servidor PostgreSQL com configuração de HA e práticas recomendadas incorporadas.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Crie um servidor PostgreSQL na fábrica de carga de trabalho do BlueXP"]
