= Atualizações de análise bem arquitetadas
:allow-uri-read: 




=== Atualizações de análise bem arquitetadas

O Workload Factory analisa seus sistemas de arquivos FSx for ONTAP em busca de *volumes NAS inativos*. A análise de configuração identifica volumes NAS que não estão sendo usados ativamente e recomenda ações para otimizar a utilização do storage e reduzir custos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementar FSx bem arquitetado para sistemas de arquivos ONTAP"]



=== Funcionalidade de tabela de diário para pontos de acesso S3

O recurso de tabela de diário oferece uma maneira de gerenciar FSx ONTAP S3 storage de objetos em escala, permitindo auditar facilmente os eventos de acesso do usuário e as operações em objetos nos seus buckets. Com o Workload Factory, você pode configurar varreduras automáticas dos seus buckets e tabelas S3 para manter um registro de eventos, mostrando todos os objetos, seus detalhes e as ações do usuário.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/setup-journal-table.html["Configure a infraestrutura da tabela de diários para NetApp Workload Factory"]



=== Suporte para gerenciamento de igroups existentes

O Workload Factory oferece suporte ao gerenciamento de igroups existentes. Você pode adicionar ou remover dispositivos de bloco e iniciadores de host para entregar sua carga de trabalho implantada no prazo.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Gerencie o armazenamento em blocos no NetApp Workload Factory"]



=== Suporte para especificar o agregado para volumes FlexVol

O Workload Factory permite criar volumes FlexVol em um agregado escolhido. Isso possibilita dividir a carga de capacidade e desempenho entre todos os recursos do sistema de arquivos.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crie um FlexVol volume no NetApp Workload Factory"]
