= Explorador de volumes
:allow-uri-read: 




[[volumes-explorer]]
=== Explorador de volumes

O Volumes Explorer oferece uma visualização simples e pesquisável de todos os seus volumes no NetApp Workload Factory. Veja rapidamente quais volumes atendem cargas de trabalho de bloco ou de arquivo. Visualize o tamanho lógico de cada volume, a capacidade física utilizada e se ele usa recursos de eficiência de storage (compressão, deduplicação e compactação). Filtre e classifique por nome, status (disponível/com falha), latência, tamanho, capacidade utilizada e recursos de proteção.



[[enhanced-email-notifications-for-replication-delays]]
=== Notificações de e-mail aprimoradas para atrasos na replicação

As notificações por e-mail sobre atrasos na replicação agora incluem mais detalhes sobre o relacionamento afetado. Essa notificação ajuda você a identificar rapidamente o relacionamento afetado e analisá-lo no console do Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Ativar notificações para atrasos na replicação"]



[[block-device-creation-enhancement]]
=== Aprimoramento da criação de dispositivos de bloco

O Workload Factory suporta a criação de dispositivos de bloco a partir de um snapshot de volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Crie um dispositivo de bloco a partir de um snapshot de volume no Workload Factory"]



[[workload-tagging-for-volumes-and-block-devices]]
=== Etiquetagem de workload para volumes e dispositivos de bloco

O Workload Factory agora identifica e etiqueta volumes e dispositivos de bloco de acordo com sua carga de trabalho ou aplicação principal. Você pode atribuir tags de carga de trabalho predefinidas, como Microsoft SQL Server ou Oracle Database, ou criar tags personalizadas para suas aplicações. As tags podem ser aplicadas a recursos individuais ou herdadas por recursos de storage conectados. Isso ajuda você a alinhar as configurações de storage com os requisitos da carga de trabalho, entender o impacto de incidentes e solucionar problemas com mais eficiência.
