= Explorador de volumes
:allow-uri-read: 




[[volumes-explorer]]
=== Explorador de volumes

O Volumes Explorer oferece uma visualização simples e pesquisável de todos os seus volumes no NetApp Workload Factory. Veja rapidamente quais volumes atendem cargas de trabalho de bloco ou de arquivo. Visualize o tamanho lógico de cada volume, a capacidade física utilizada e se ele usa recursos de eficiência de storage (compressão, deduplicação e compactação). Filtre e classifique por nome, status (disponível/com falha), latência, tamanho, capacidade utilizada e recursos de proteção.



[[enhanced-email-notifications-for-replication-delays]]
=== Notificações de e-mail aprimoradas para atrasos na replicação

As notificações por e-mail sobre atrasos na replicação agora incluem mais detalhes sobre o relacionamento afetado. Essa notificação ajuda você a identificar rapidamente o relacionamento afetado e analisá-lo no console do Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Ativar notificações para atrasos na replicação"]



[[block-device-creation-enhancement]]
=== Aprimoramento da criação de dispositivos de bloco

O Workload Factory suporta a criação de dispositivos de bloco a partir de um snapshot de volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Crie um dispositivo de bloco a partir de um snapshot de volume no Workload Factory"]
